#!/bin/bash

export PYTHONUNBUFFERED=1


cd /mail


echo
echo '>>> Configurando domínio'
cat _main.cf | sed -e "s/{{ DOMINIO }}/$CARTEIRO_DOMINIO/g" > main.cf
cat _virtual | sed -e "s/{{ DOMINIO }}/$CARTEIRO_DOMINIO/g" > virtual
service syslog-ng start
postmap /etc/postfix/virtual


cd /root


echo
echo '>>> Configurando inbox'
mkdir -p /root/Maildir/new


echo
echo '>>> Criando virtualenv'
python3 -m venv .venv
source .venv/bin/activate


echo
echo '>>> Instalando dependências'
python3 -m pip install -r /mail/requirements.txt


echo
echo '>>> Iniciando watcher'
/mail/watcher &


echo
echo '>>> Iniciando postfix'
postfix start-fg &


cd /mail/app


echo
echo '>>> Iniciando app'
python3 manage.py migrate
python3 manage.py runserver 0.0.0.0:8000

